name: Deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - main  # Adjust if your default branch is different (e.g., 'master')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug directory structure
        run: |
          ls -la
          ls -la app/ || echo "No app directory"
          ls -la app/templates/ || echo "No templates directory"
          ls -la app/static/ || echo "No static directory"

      - name: Freeze Flask app
        run: |
          python freeze.py 2>&1 | tee freeze_output.log
          cat freeze_output.log

      - name: Debug build directory
        run: |
          ls -la build/ || echo "No build directory"
          find build -type f | sort

      - name: Rename files to include .html
        run: |
          cd build
          for file in *; do
            if [ -f "$file" ] && [ "$file" != "index.html" ] && [[ "$file" != *.html ]]; then
              mv "$file" "$file.html"
            fi
          done
          ls -la
  
      - name: List build directory contents
        run: |
          ls -la build/ || echo "Build directory not found"
          ls -la build/static/ || echo "Static directory not found"

      - name: Create .nojekyll file
        run: touch build/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build  # The folder to deploy
          branch: gh-pages  # The branch to deploy to
          clean: true