name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check directory structure
      run: |
        ls -la app/
        ls -la app/templates/ || echo "Templates directory not found"
        ls -la app/static/ || echo "Static directory not found"
    
    - name: Freeze Flask app
      run: |
        ls -la
        python -v freeze.py 2>&1 | tee freeze_output.log
        cat freeze_output.log
      
    - name: Move build files to root
      run: |
        mkdir -p build
        mv app/build/* build/ || { echo "No files found in app/build/"; ls -la app/build/; exit 1; }
        ls -la build/
    
    - name: List build directory contents
      run: |
        ls -la build/ || echo "Build directory not found"
        ls -la build/static/ || echo "Static directory not found"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        force_orphan: true
        keep_files: false
        publish_branch: gh-pages